/** Cadenas de interfaz centralizadas (es-ES) para facilitar una futura traducción. */
export const STR = {
  titulo: 'Pokémon Tactical Arena',
  subtitulo: 'Fan game táctico no oficial · sin ánimo de lucro',
  jugarBots: 'Jugar con bots',
  crearSala: 'Crear sala',
  unirse: 'Unirse a sala',
  entrenamiento: 'Entrenamiento',
  ajustes: 'Ajustes',
  creditos: 'Créditos',
  volver: 'Volver',
  continuar: 'Continuar',
  cancelar: 'Cancelar',
  aceptar: 'Aceptar',
  salir: 'Salir',
  alias: 'Alias (2–16 caracteres)',
  codigoSala: 'Código de sala',
  equipoAzul: 'Equipo Azul',
  equipoNaranja: 'Equipo Naranja',
  atacantes: 'Atacantes',
  defensores: 'Defensores',
  listo: 'Listo',
  iniciarPartida: 'Iniciar partida',
  esperandoAnfitrion: 'Esperando al anfitrión…',
  seleccionPersonaje: 'Selección de personaje',
  compra: 'Compra',
  saldo: 'Créditos',
  comprado: 'Comprado',
  equipado: 'Equipado',
  marcador: 'Marcador',
  bajas: 'Bajas',
  muertes: 'Muertes',
  asistencias: 'Asistencias',
  dano: 'Daño',
  ronda: 'Ronda',
  preparacion: 'Preparación',
  rondaActiva: '¡Ronda en marcha!',
  nucleoInstalado: '¡Núcleo instalado!',
  nucleoDesactivado: 'Núcleo desactivado',
  nucleoSoltado: 'Núcleo en el suelo',
  nucleoRecogido: 'Núcleo recuperado',
  llevasNucleo: 'Llevas el núcleo',
  instalando: 'Instalando…',
  desactivando: 'Desactivando…',
  victoriaRonda: 'Ronda para el equipo',
  cambioMitad: 'Cambio de mitad: se intercambian los roles',
  victoria: '¡Victoria!',
  derrota: 'Derrota',
  empate: 'Empate',
  resultado: 'Resultado',
  ganador: 'Ganador',
  volverMenu: 'Volver al menú',
  conexionPerdida: 'Conexión perdida',
  reconectando: 'Reconectando…',
  desconectado: 'Desconectado del servidor',
  controles: 'Controles',
  sensibilidad: 'Sensibilidad del ratón',
  invertirY: 'Invertir eje Y',
  fov: 'Campo de visión (FOV)',
  volumenGeneral: 'Volumen general',
  volumenMusica: 'Volumen de música',
  volumenEfectos: 'Volumen de efectos',
  calidad: 'Calidad gráfica',
  calidadBaja: 'Baja',
  calidadMedia: 'Media',
  calidadAlta: 'Alta',
  movimientoReducido: 'Modo de movimiento reducido',
  destelloAccesible: 'Destello accesible (oscurecer)',
  restaurarControles: 'Restaurar controles predeterminados',
  pulsaTecla: 'Pulsa una tecla…',
  webglNoDisponible: 'Tu navegador no dispone de WebGL. El juego necesita WebGL para dibujar la escena 3D. Prueba a actualizar el navegador o a activar la aceleración gráfica.',
  cargando: 'Cargando…',
  reintentar: 'Reintentar',
  errorCarga: 'Error al cargar un recurso.',
  salaNoExiste: 'La sala no existe.',
  salaLlena: 'La sala está llena.',
  nombreInvalido: 'Alias no válido (2–16 caracteres).',
  comprarFueraDeFase: 'Solo se compra en preparación.',
  cambioPersonajeAviso: 'Cambiar de personaje elimina la carga de habilidad comprada, sin reembolso. ¿Continuar?',
  sitioA: 'Zona A',
  sitioB: 'Zona B',
  supervivientes: 'vivos',
  derrotaConsecutiva: 'racha de derrotas',
  faseFin: 'Fin de la partida',
  anfitrion: 'Anfitrión',
  bot: 'BOT',
  practicaNucleo: 'Núcleo de práctica',
  munecos: 'Muñecos de práctica',
  spectating: 'Observando a',
  cambiaConFuego: 'Clic para cambiar de aliado',
} as const;
